<div style="display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 25px">
    <img class="image-style-align-left" src="/public/ckfinder/userfiles/images/1.jpg" style="width: 49%">
    <div style="padding: 10px 15px; width: 49%; text-align: justify;">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id et vehicula leo aliquet vivamus. Dignissim feugiat donec et diam elementum, malesuada in dis egestas. Viverra tincidunt id tellus egestas. Vel posuere aenean cras id vel tristique urna. Imperdiet id velit diam, quis viverra. Purus fames eget pulvinar turpis massa orci et. Vitae orci morbi tristique aliquet id. Faucibus semper penatibus diam turpis lacus, sed malesuada nunc facilisis. Mi arcu nulla sed quis. Morbi id ornare et ornare ipsum erat nulla. Urna ultricies neque consectetur mattis. Est scelerisque nec dis curabitur urna ultricies feugiat. Venenatis orci, egestas dolor ut. Elit enim semper mauris pellentesque ac. Porta a eget donec sed elit suspendisse scelerisque pretium. Lectus ut dolor enim porta velit. Fermentum, ac odio aliquam, arcu, gravida. Nulla nisi, amet bibendum etiam turpis sagittis amet netus odio. Fermentum facilisi etiam tellus etiam pulvinar risus at nisl duis. Sapien tortor at tincidunt convallis vitae porta nec. Quis nunc odio mauris sed varius sit. Volutpat massa in elementum orci enim cursus arcu vitae. Ac auctor tempor gravida morbi leo malesuada faucibus sit nisl. Rutrum accumsan volutpat a libero ut arcu. Quis sit nunc consectetur nec. Varius odio a magna lectus dolor non. Ut pulvinar ultrices lorem nam ultricies dui. Pulvinar lobortis lorem vivamus in eros, et amet. Volutpat mattis a, tellus hendrerit laoreet viverra pellentesque. Condimentum tristique velit, aliquam ornare eu quisque vulputate. Morbi imperdiet lacus, lacus aliquam. Non tellus turpis sit quam sit. Nibh pellentesque enim magnis elementum, libero, eget ut sed. Libero tellus, id montes, eget diam cras ullamcorper dui. Nulla scelerisque porta nunc eget consectetur. Rhoncus tempus netus lectus amet lobortis orci donec. Accumsan id vulputate massa, sit at.
    </div>
</div>
<div style="display: flex; align-items: flex-start; justify-content: space-between">
    <div style="padding: 10px 15px; width: 49%; text-align: justify; ">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Id et vehicula leo aliquet vivamus. Dignissim feugiat donec et diam elementum, malesuada in dis egestas. Viverra tincidunt id tellus egestas. Vel posuere aenean cras id vel tristique urna. Imperdiet id velit diam, quis viverra. Purus fames eget pulvinar turpis massa orci et. Vitae orci morbi tristique aliquet id. Faucibus semper penatibus diam turpis lacus, sed malesuada nunc facilisis. Mi arcu nulla sed quis. Morbi id ornare et ornare ipsum erat nulla. Urna ultricies neque consectetur mattis. Est scelerisque nec dis curabitur urna ultricies feugiat. Venenatis orci, egestas dolor ut. Elit enim semper mauris pellentesque ac. Porta a eget donec sed elit suspendisse scelerisque pretium. Lectus ut dolor enim porta velit. Fermentum, ac odio aliquam, arcu, gravida. Nulla nisi, amet bibendum etiam turpis sagittis amet netus odio. Fermentum facilisi etiam tellus etiam pulvinar risus at nisl duis. Sapien tortor at tincidunt convallis vitae porta nec. Quis nunc odio mauris sed varius sit. Volutpat massa in elementum orci enim cursus arcu vitae. Ac auctor tempor gravida morbi leo malesuada faucibus sit nisl. Rutrum accumsan volutpat a libero ut arcu. Quis sit nunc consectetur nec. Varius odio a magna lectus dolor non. Ut pulvinar ultrices lorem nam ultricies dui. Pulvinar lobortis lorem vivamus in eros, et amet. Volutpat mattis a, tellus hendrerit laoreet viverra pellentesque. Condimentum tristique velit, aliquam ornare eu quisque vulputate. Morbi imperdiet lacus, lacus aliquam. Non tellus turpis sit quam sit. Nibh pellentesque enim magnis elementum, libero, eget ut sed. Libero tellus, id montes, eget diam cras ullamcorper dui. Nulla scelerisque porta nunc eget consectetur. Rhoncus tempus netus lectus amet lobortis orci donec. Accumsan id vulputate massa, sit at.
    </div>
    <img class="image-style-align-right" src="/public/ckfinder/userfiles/images/2(1).jpg" style="width: 49%">
</div>
